root_dir: /mnt/d/dataset/CameraCalib/stereoexample_github/stereoexample_zed/calib/1920new     # 标定图像的目录,目录下就是图像
Camera_SensorType: Pinhole      # 支持: Pinhole, Fisheye, Omnidir
Camera_NumType: Stereo       # 支持: Monocular, Stereo
square_size: 0.024               # 单位距离，比如每格边长 m
board_size: [3, 4]              # 棋盘格规格: 行数7, 列数6
board_type: Circle              # 支持: Corner 或 Circle
raduis_size: [5, 5] 
criteria: [3, 100, 1e-7]        # 终止条件: cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER
flag: 0                         # 标定标志位（opencv 标志组合）
save_dir: ./new
#  CSV数据加载选项
use_csv_data: true              # 是否使用CSV数据而非从图像检测角点，运行完false后可以设置为true试一下
image_points_dir: new       
world_points_file: new/world_coordinates.csv # 世界坐标点CSV文件