root_dir: data/corner/          # 左右图像的目录，还有left和right目录，分别装着左图和右图
Camera_SensorType: Pinhole      # 支持: Pinhole, Fisheye
Camera_NumType: Stereo          # 支持: Monocular, Stereo
square_size: 0.02               # 单位距离，比如每格边长 m
board_size: [9, 6]              # 棋盘格规格: 行数7, 列数6
board_type: Corner              # 支持: Corner 或 Circle
raduis_size: [5, 5] 
criteria: [3, 100, 1e-7]        # 终止条件: cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER
flag: 0                         # 标定标志位（opencv 标志组合）
save_dir: ./stereocorner        # 保存目录
alpha: 0.

#  CSV数据加载选项
use_csv_data: false                  # 是否使用CSV数据而非从图像检测角点，运行完false后可以设置为true试一下
image_points_dir: stereocorner       # 双目：目录下应该还有left_corners和right_corners文件夹
world_points_file: stereocorner/world_coordinates.csv # 世界坐标点CSV文件